---
- name: Update apt cache (Debian)
  when: ansible_os_family == 'Debian'
  tags: molecule-idempotence-notest
  apt:
    update_cache: true

- name: Install xl2tpd and strongswan
  notify:
    - reboot system
  package:
    name:
      - xl2tpd
      - libreswan
    state: present
  tags:
    - l2tp-config

- name: check if blacklist file exists
  stat:
    path: /etc/modprobe.d/l2tp_netlink-blacklist.conf
  register: l2tp_netlink_blacklist
  tags:
    - l2tp-config

- name: check if blacklist file exists
  stat:
    path: /etc/modprobe.d/l2tp_ppp-blacklist.conf
  register: l2tp_ppp_blacklist
  tags:
    - l2tp-config

- name: Disable l2tp_netlink kernel module blocklist
  when: l2tp_netlink_blacklist.stat.exists == True
  lineinfile:
    dest: /etc/modprobe.d/l2tp_netlink-blacklist.conf
    regexp: "^blacklist l2tp_netlink"
    line: "#blacklist l2tp_netlink"
    state: present
  notify:
    - reboot system
  tags:
    - l2tp-config

- name: Disable l2tp_ppp kernel module blocklist
  when: l2tp_ppp_blacklist.stat.exists == True
  lineinfile:
    dest: /etc/modprobe.d/l2tp_ppp-blacklist.conf
    regexp: "^blacklist l2tp_ppp"
    line: "#blacklist l2tp_ppp"
    state: present
  notify:
    - reboot system
  tags:
    - l2tp-config

- name: Reboot is needed to load kernel modules
  meta: flush_handlers
  tags:
    - l2tp-config

- name: Place /etc/ipsec.conf
  notify: restart ipsec
  ansible.builtin.template:
    src: ipsec.conf.j2
    dest: "{{ ipsec_config_location }}"
    owner: root
    group: root
    mode: "0640"
  tags:
    - l2tp-config

# - name: Place strongswan config
#   ansible.builtin.template:
#     src: swanctl.conf.j2
#     dest: "{{ swanctl_config_location }}"
#     owner: root
#     group: root
#     mode: "0640"
#   notify:
#     - restart ipsec

- name: Place /etc/ppp/chap-secrets
  ansible.builtin.template:
    src: chap-secrets.j2
    dest: "/etc/ppp/chap-secrets"
    owner: root
    group: root
    mode: "0600"
  tags:
    - l2tp-auth-config

- name: Place /etc/ppp/options.xl2tpd
  ansible.builtin.template:
    src: options.xl2tpd.j2
    dest: "/etc/ppp/options.xl2tpd"
    owner: root
    group: root
    mode: "0640"
  tags:
    - l2tp-auth-config

- name: Place /etc/xl2tpd/xl2tpd.conf
  ansible.builtin.template:
    src: xl2tpd.conf.j2
    dest: "/etc/xl2tpd/xl2tpd.conf"
    owner: root
    group: root
    mode: "0640"
  notify:
    - restart xl2tpd

- name: Register if ipsec secrets file already exists on target host
  ansible.builtin.stat:
    path: "{{ ipsec_secret_file_location }}"
  register: ipsec_secrets_register_file

- name: Handling for existing IPSec PSK
  tags:
    - l2tp-auth-config
  when: 
    - default_ipsec_psk is not defined
    - generate_ipsec_psk
    - not ipsec_secrets_register_file.stat.exists
  block:
    - name: Generate IPSec PSK
      notify: restart ipsec
      register: gen_ipsec_psk
      command: openssl rand -hex 35

    - name: Set IPSec PSK fact
      notify: restart ipsec
      set_fact:
        default_ipsec_psk: "{{ gen_ipsec_psk.stdout }}"

    - debug:
        msg: "Generated ipsec psk: {{ default_ipsec_psk }}"

- name: Place {{ ipsec_secret_file_location }}
  when:
    - not ipsec_secrets_register_file.stat.exists
    - configure_ipsec_secret
    - default_ipsec_psk is defined
  ansible.builtin.template:
    src: ipsec.secrets.j2
    dest: "{{ ipsec_secret_file_location }}"
    owner: root
    group: root
    mode: "0600"
  notify:
    - restart ipsec

- name: Ensure ipsec is started and enabled
  service:
    name: "{{ ipsec_package_name }}"
    state: started
    enabled: true
  tags:
    - l2tp-config

- name: Ensure xl2tpd is started and enabled
  service:
    name: xl2tpd
    state: started
    enabled: true
  tags:
    - l2tp-config

- name: Pause for 5 seconds (Services starting)
  ansible.builtin.pause:
    seconds: 5
  tags:
    - l2tp-config

- name: Verify ipsec config
  tags: 
    - molecule-idempotence-notest
    - l2tp-config
  command: ipsec verify
