---
- name: reboot system
  reboot:
    msg: "Reboot initiated by Ansible to load new kernel modules"

- name: restart ssh
  service: name=sshd state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart ipsec
  service: name=ipsec state=restarted

- name: reload ufw
  service: name=ufw state=restarted

- name: restart firewalld
  command: firewall-cmd --reload

- name: restart ipsec
  service: name={{ ipsec_package_name }} state=restarted enabled=yes

- name: restart xl2tpd
  service: name=xl2tpd state=restarted enabled=yes
