---
- name: Set sysctl parameters
  sysctl:
    name: "{{ item.parameter }}"
    value: "{{ item.value }}"
    sysctl_set: true
  with_items:
    - {parameter: 'net.ipv4.ip_forward', value: '1'}
    - {parameter: 'net.ipv4.conf.all.send_redirects', value: '0'}
    - {parameter: 'net.ipv4.conf.default.send_redirects', value: '0'}
    - {parameter: 'net.ipv4.conf.all.rp_filter', value: '0'}

- ufw:
    rule: allow
    route: true
    comment: Created by Ansible
    src: 10.10.10.0/24
    dest: 0.0.0.0/0

- name: Allow routing from private IPs
  community.general.ufw:
    rule: allow
    route: true
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: '10.0.0.0/8', dest: '0.0.0.0/0'}
    - {src: '172.16.0.0/12', dest: '0.0.0.0/0'}
    - {src: '192.168.0.0/16', dest: '0.0.0.0/0'}

- name: Setup nat table rules with MASQUERADE - ufw
  blockinfile:
    dest: /etc/ufw/before.rules
    state: present
    insertbefore: \*filter
    block: |
      # Managed by Ansible. L2TP IPSec config.
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -s 10.10.10.0/24 -o {{
       ansible_default_ipv4.interface }} -j MASQUERADE
      -A POSTROUTING -s 10.10.10.0/24 -o {{ ansible_default_ipv4.interface
      }} -m policy --pol ipsec --dir out -j ACCEPT
      COMMIT
  notify:
    - reload ufw
