---
- name: Converge
  hosts: all

  vars:
    upgrade_packages: false

  tasks:
    - name: Update apt cache (on Debian).
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  roles:
    - role: android06.security
    - role: l2tp-ipsec-ansible

# - import_playbook: ../../main.yml
