---
- name: Converge
  hosts: all

  tasks:
    - name: Create /var/run/sshd (Debian)
      when: ansible_os_family == 'Debian'
      file:
        path: /var/run/sshd
        state: directory
        owner: root
        group: root
        mode: '0751'

    - name: Create kernel modules directory (Debian)
      when: ansible_os_family == 'Debian'
      file:
        path: /lib/modules
        state: directory
        mode: '0751'

    - name: Create a symbolic link
      file:
        src: "/host/lib/modules/{{ ansible_kernel }}"
        dest: "/lib/modules/{{ ansible_kernel }}"
        owner: root
        group: root
        state: link

    - name: Update apt cache (on Debian).
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install openssh-server (on RedHat).
      package:
        name: openssh-server
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install selinux-policy (on RedHat).
      package:
        name: selinux-policy
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install openssh-server (on Debian).
      apt:
        name: openssh-server
        state: present
      when: ansible_os_family == 'Debian'

    - name: Generate SSH keys
      tags: molecule-idempotence-notest
      command: ssh-keygen -A

- import_playbook: ../../main.yml
