---
dependency:
  name: galaxy
lint: |
  set -e
#  yamllint .
#  ansible-lint
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox

platforms:
  - name: test-wg-ubuntu2004
    box: geerlingguy/${MOLECULE_DISTRO:-ubuntu2004}
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
