---
- name: Verify
  hosts: all
  vars_files:
    - ../../roles/role.android06.l2tp-ipsec/vars/main.yml

  tasks:
    - name: Verify that ipsec is running
      systemd:
        name: ipsec.service
        enabled: true
        state: started
      check_mode: true
      register: ipsec_service
      failed_when: ipsec_service is changed

    - name: Verify that xl2tpd is running
      systemd:
        name: xl2tpd.service
        enabled: true
        state: started
      check_mode: true
      register: xl2tpd_service
      failed_when: xl2tpd_service is changed
